version: '3'

services:
  postgres:
    container_name: postgres_container
    environment:
      POSTGRES_DB: service_db
      POSTGRES_PASSWORD: example
      POSTGRES_USERNAME: postgres
    image: postgres:12.3
  web:
    build: .
    container_name: app_container
    command: bash -c "bundle exec rackup -p 8080"
    env_file:
      - .env.docker
    environment:
      POSTGRES_DB: service_db
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_USERNAME: postgres
    volumes:
      - .:/docker
    ports:
      - "8080:8080"
    depends_on:
      - postgres
