version: '3'

services:
  postgres:
    container_name: postgres_container
    env_file:
      - .env.docker
    image: postgres:12.3
  web:
    build: .
    container_name: app_container
    command: bash -c "bundle exec rackup -p 8080"
    env_file:
      - .env.docker
    volumes:
      - .:/docker
    ports:
      - "8080:8080"
    depends_on:
      - postgres
