default: &default
  adapter: postgresql
  database: <%= ENV['POSTGRES_DB'] %>
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USERNAME'] %>

development:
  <<: *default

test:
  <<: *default
  database: <%= "#{ENV['POSTGRES_DB']}_test" %>

production:
  <<: *default
  password: <%= ENV['POSTGRES_PASSWORD'] %>
