default: &default
  adapter: postgresql
  database: <%= ENV['DATABASE_NAME'] %>
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] %>

development:
  <<: *default

test:
  <<: *default
  database: <%= "#{ENV['DATABASE_NAME']}_test" %>

production:
  <<: *default
  password: <%= ENV['DATABASE_PASSWORD'] %>
